docker run -it --cap-add=NET_ADMIN qeeqbox/kali:1.0
...
...
Successfully built 7c36ab06e878
Successfully tagged qeeqbox/kali:1.0

https://github.com/qeeqbox/docker-images

Custom Kali distro accessible via VNC, RDP or web browser

root pass -> EmBNjt^Zea
-----------------------
Username  -> xuser
Password  -> xTk#gV8ig*
VNC pass  -> fjw#8fAwVC

http://172.17.0.2:6080/index.html
